version: 1
accounts:
  - name: alice
    coins: ["1000000000uatom", "650000000000ugtfx"]
  - name: joy
    coins: ["1000000000uatom", "650000000000ugtfx"]
validators:
  - name: alice
    bonded: "100000000ugtfx"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: joy
  coins: ["100000000ugtfx"]
genesis:
  chain_id: "gitshock-1"
  app_state:
    staking:
      params:
        bond_denom: "ugtfx"
    crisis:
      constant_fee:
        denom: "ugtfx"
    gov:
      deposit_params:
        min_deposit:
          - "amount": "100000"
            "denom": "ugtfx"
    mint:
      params:
        mint_denom: "ugtfx"